-- Canonical listing read model used by search, detail, maps, Jamie, and PowerSync.

ALTER TABLE public.properties
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS street TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS amenities TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS images TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS price_type TEXT NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS rates JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'MLS',
  ADD COLUMN IF NOT EXISTS listing_status TEXT NOT NULL DEFAULT 'Active',
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS display_public BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE public.properties
  DROP CONSTRAINT IF EXISTS properties_price_type_check;

ALTER TABLE public.properties
  ADD CONSTRAINT properties_price_type_check
  CHECK (price_type IN ('sale', 'lease', 'unknown'));

UPDATE public.properties
SET
  images = CASE
    WHEN cardinality(images) = 0 AND image_url IS NOT NULL THEN ARRAY[image_url]
    ELSE images
  END
WHERE deleted_at IS NULL;

-- Backfill only known public IDX provider rows with media. Other records remain
-- private until an ingestion adapter explicitly confirms display authorization.
UPDATE public.properties
SET display_public = true
WHERE deleted_at IS NULL
  AND is_demo = false
  AND source = 'MLS'
  AND lower(COALESCE(metadata->>'provider', '')) IN ('repliers', 'bridge')
  AND (cardinality(images) > 0 OR image_url IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_properties_listing_status
  ON public.properties(listing_status);
CREATE INDEX IF NOT EXISTS idx_properties_public_active
  ON public.properties(display_public, listing_status)
  WHERE deleted_at IS NULL AND is_demo = false;
CREATE INDEX IF NOT EXISTS idx_properties_coordinates
  ON public.properties(latitude, longitude)
  WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

DROP POLICY IF EXISTS "Public properties are viewable by everyone." ON public.properties;
DROP POLICY IF EXISTS "Public IDX listings are viewable." ON public.properties;
CREATE POLICY "Public IDX listings are viewable."
ON public.properties FOR SELECT
TO anon, authenticated
USING (display_public = true AND deleted_at IS NULL AND is_demo = false);

DROP POLICY IF EXISTS "Service role can manage properties." ON public.properties;
CREATE POLICY "Service role can manage properties."
ON public.properties FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.mls_sync_runs (
  id TEXT PRIMARY KEY,
  provider TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
  params JSONB NOT NULL DEFAULT '{}'::jsonb,
  received INTEGER NOT NULL DEFAULT 0,
  synced INTEGER NOT NULL DEFAULT 0,
  skipped INTEGER NOT NULL DEFAULT 0,
  failed INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  duration_ms BIGINT
);

CREATE TABLE IF NOT EXISTS public.mls_sync_failures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES public.mls_sync_runs(id) ON DELETE CASCADE,
  mls_id TEXT,
  name TEXT,
  error TEXT NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.mls_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_sync_failures ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role manages MLS sync runs."
ON public.mls_sync_runs FOR ALL TO service_role
USING (true) WITH CHECK (true);

CREATE POLICY "Service role manages MLS sync failures."
ON public.mls_sync_failures FOR ALL TO service_role
USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_mls_sync_runs_started_at
  ON public.mls_sync_runs(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_mls_sync_failures_run_id
  ON public.mls_sync_failures(run_id);

CREATE TABLE IF NOT EXISTS public.mls_sync_leases (
  lock_name TEXT PRIMARY KEY,
  owner_id TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.mls_sync_leases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manages MLS sync leases." ON public.mls_sync_leases;
CREATE POLICY "Service role manages MLS sync leases."
ON public.mls_sync_leases FOR ALL TO service_role
USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.acquire_mls_sync_lease(
  p_lock_name TEXT,
  p_owner_id TEXT,
  p_ttl_seconds INTEGER DEFAULT 1800
) RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  acquired BOOLEAN := false;
BEGIN
  INSERT INTO public.mls_sync_leases(lock_name, owner_id, expires_at, updated_at)
  VALUES (p_lock_name, p_owner_id, now() + make_interval(secs => p_ttl_seconds), now())
  ON CONFLICT (lock_name) DO UPDATE
    SET owner_id = EXCLUDED.owner_id,
        expires_at = EXCLUDED.expires_at,
        updated_at = now()
    WHERE public.mls_sync_leases.expires_at <= now()
       OR public.mls_sync_leases.owner_id = EXCLUDED.owner_id
  RETURNING true INTO acquired;

  RETURN COALESCE(acquired, false);
END;
$$;

CREATE OR REPLACE FUNCTION public.release_mls_sync_lease(
  p_lock_name TEXT,
  p_owner_id TEXT
) RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  DELETE FROM public.mls_sync_leases
  WHERE lock_name = p_lock_name AND owner_id = p_owner_id;
$$;

REVOKE ALL ON FUNCTION public.acquire_mls_sync_lease(TEXT, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.release_mls_sync_lease(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.acquire_mls_sync_lease(TEXT, TEXT, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_mls_sync_lease(TEXT, TEXT) TO service_role;
