-- NTREIS / MLS listing detail schema.
--
-- Keep public listing-card fields in public.properties. These side tables store
-- full MLS sheet detail from NTREIS-style reports without bloating homepage
-- queries. Private/showing/contact fields are isolated behind service-role RLS.

CREATE TABLE IF NOT EXISTS public.mls_listing_details (
  property_id UUID PRIMARY KEY REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL UNIQUE,
  source_system TEXT NOT NULL DEFAULT 'NTREIS',
  property_type TEXT,
  property_subtype TEXT,
  listing_status TEXT,
  list_price NUMERIC(14,2),
  original_list_price NUMERIC(14,2),
  list_price_per_sqft NUMERIC(12,2),
  price_change_summary TEXT,
  price_changed_at DATE,
  also_for_lease BOOLEAN,
  lease_mls_id TEXT,
  subdivision TEXT,
  county TEXT,
  country TEXT,
  lake_name TEXT,
  parcel_id TEXT,
  parcel_id_2 TEXT,
  lot TEXT,
  block TEXT,
  legal_description TEXT,
  unexempt_taxes NUMERIC(14,2),
  pid TEXT,
  multi_parcel BOOLEAN,
  mud_district BOOLEAN,
  special_tax_authority BOOLEAN,
  year_built INTEGER,
  year_built_source TEXT,
  living_area_count INTEGER,
  dining_area_count INTEGER,
  fireplace_count INTEGER,
  bedroom_count INTEGER,
  bathroom_total NUMERIC(4,1),
  bathroom_full INTEGER,
  bathroom_half INTEGER,
  pool BOOLEAN,
  garage BOOLEAN,
  garage_spaces INTEGER,
  attached_garage BOOLEAN,
  covered_parking_spaces INTEGER,
  garage_size TEXT,
  handicap_amenities BOOLEAN,
  horses_permitted BOOLEAN,
  proposed_financing TEXT[],
  possession TEXT,
  listing_terms TEXT[],
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_land (
  property_id UUID PRIMARY KEY REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL UNIQUE,
  lot_size_sqft NUMERIC(14,2),
  lot_size_acres NUMERIC(12,4),
  lot_dimensions TEXT,
  road_frontage_type TEXT,
  road_surface TEXT,
  crops_grasses TEXT[],
  soil_type TEXT,
  fencing TEXT[],
  vegetation TEXT[],
  lot_description TEXT[],
  current_use TEXT[],
  proposed_use TEXT[],
  present_use TEXT[],
  restrictions TEXT[],
  easements TEXT[],
  utilities TEXT[],
  street_utilities TEXT[],
  hoa_name TEXT,
  hoa_company TEXT,
  hoa_website TEXT,
  hoa_management_email TEXT,
  hoa_fee_description TEXT,
  subdivision_features TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_schools (
  property_id UUID PRIMARY KEY REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL UNIQUE,
  district TEXT,
  elementary TEXT,
  primary_school TEXT,
  middle_school TEXT,
  junior_high TEXT,
  high_school TEXT,
  senior_high TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id UUID NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL,
  room_name TEXT NOT NULL,
  dimensions TEXT,
  level TEXT,
  features TEXT[],
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_attributes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id UUID NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL,
  section TEXT NOT NULL,
  label TEXT NOT NULL,
  value_text TEXT,
  value_list TEXT[],
  value_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_farm_ranch (
  property_id UUID PRIMARY KEY REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL UNIQUE,
  residences_count INTEGER,
  tank_pond_count INTEGER,
  barn_count INTEGER,
  lake_count INTEGER,
  pasture_acres NUMERIC(12,4),
  cultivated_acres NUMERIC(12,4),
  bottom_land_acres NUMERIC(12,4),
  irrigated_acres NUMERIC(12,4),
  crop_retirement_program TEXT,
  aerial_photo_available BOOLEAN,
  ag_exemption BOOLEAN,
  land_leased BOOLEAN,
  road_frontage TEXT,
  wells_count INTEGER,
  horse_amenities TEXT[],
  miscellaneous TEXT[],
  other_equipment TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_structures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id UUID NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL,
  structure_type TEXT NOT NULL,
  description TEXT,
  stalls_count INTEGER,
  size TEXT,
  features TEXT[],
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_public_remarks (
  property_id UUID PRIMARY KEY REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL UNIQUE,
  property_description TEXT,
  exclusions TEXT,
  public_driving_directions TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_private_remarks (
  property_id UUID PRIMARY KEY REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL UNIQUE,
  private_remarks TEXT,
  showing_instructions TEXT,
  included_items TEXT,
  excluded_items TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_financials (
  property_id UUID PRIMARY KEY REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL UNIQUE,
  loan_type TEXT,
  payment_type TEXT,
  seller_concessions BOOLEAN,
  balance TEXT,
  lender TEXT,
  payment TEXT,
  original_date DATE,
  second_mortgage BOOLEAN,
  cumulative_days_on_market INTEGER,
  days_on_market INTEGER,
  list_type TEXT,
  list_date DATE,
  expiration_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_contacts (
  property_id UUID PRIMARY KEY REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL UNIQUE,
  list_office_name TEXT,
  list_office_code TEXT,
  list_office_phone TEXT,
  list_office_address TEXT,
  list_office_fax TEXT,
  broker_license TEXT,
  list_office_email TEXT,
  list_agent_name TEXT,
  list_agent_phone TEXT,
  list_agent_email TEXT,
  list_agent_license TEXT,
  list_agent_fax TEXT,
  list_agent_other_phone TEXT,
  list_agent_texting_allowed BOOLEAN,
  list_office_supervisor_name TEXT,
  list_office_supervisor_id TEXT,
  list_office_supervisor_phone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_showing (
  property_id UUID PRIMARY KEY REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL UNIQUE,
  call_instructions TEXT,
  appointment_phone TEXT,
  keybox_number TEXT,
  keybox_type TEXT,
  owner_name TEXT,
  seller_type TEXT,
  showing_instructions TEXT,
  access_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mls_listing_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id UUID NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  mls_id TEXT NOT NULL,
  media_type TEXT NOT NULL DEFAULT 'image',
  url TEXT NOT NULL,
  caption TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  width INTEGER,
  height INTEGER,
  source TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT mls_listing_media_type_check CHECK (media_type IN ('image', 'virtual_tour', 'video', 'document', 'other')),
  CONSTRAINT mls_listing_media_url_check CHECK (url ~* '^https?://')
);

CREATE INDEX IF NOT EXISTS idx_mls_listing_details_mls_id ON public.mls_listing_details(mls_id);
CREATE INDEX IF NOT EXISTS idx_mls_listing_land_mls_id ON public.mls_listing_land(mls_id);
CREATE INDEX IF NOT EXISTS idx_mls_listing_rooms_property ON public.mls_listing_rooms(property_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_mls_listing_attributes_property_section ON public.mls_listing_attributes(property_id, section, sort_order);
CREATE INDEX IF NOT EXISTS idx_mls_listing_structures_property ON public.mls_listing_structures(property_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_mls_listing_media_property ON public.mls_listing_media(property_id, sort_order);

ALTER TABLE public.mls_listing_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_land ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_schools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_attributes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_farm_ranch ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_structures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_public_remarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_private_remarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_financials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_showing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mls_listing_media ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_public_property(p_property_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.properties p
    WHERE p.id = p_property_id
      AND p.display_public = true
      AND COALESCE(p.is_demo, false) = false
      AND p.deleted_at IS NULL
  );
$$;

REVOKE ALL ON FUNCTION public.is_public_property(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_public_property(UUID) TO anon, authenticated, service_role;

DROP POLICY IF EXISTS "Public MLS details are viewable for public properties." ON public.mls_listing_details;
CREATE POLICY "Public MLS details are viewable for public properties."
ON public.mls_listing_details FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DROP POLICY IF EXISTS "Public MLS land details are viewable for public properties." ON public.mls_listing_land;
CREATE POLICY "Public MLS land details are viewable for public properties."
ON public.mls_listing_land FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DROP POLICY IF EXISTS "Public MLS schools are viewable for public properties." ON public.mls_listing_schools;
CREATE POLICY "Public MLS schools are viewable for public properties."
ON public.mls_listing_schools FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DROP POLICY IF EXISTS "Public MLS rooms are viewable for public properties." ON public.mls_listing_rooms;
CREATE POLICY "Public MLS rooms are viewable for public properties."
ON public.mls_listing_rooms FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DROP POLICY IF EXISTS "Public MLS attributes are viewable for public properties." ON public.mls_listing_attributes;
CREATE POLICY "Public MLS attributes are viewable for public properties."
ON public.mls_listing_attributes FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DROP POLICY IF EXISTS "Public MLS farm ranch details are viewable for public properties." ON public.mls_listing_farm_ranch;
CREATE POLICY "Public MLS farm ranch details are viewable for public properties."
ON public.mls_listing_farm_ranch FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DROP POLICY IF EXISTS "Public MLS structures are viewable for public properties." ON public.mls_listing_structures;
CREATE POLICY "Public MLS structures are viewable for public properties."
ON public.mls_listing_structures FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DROP POLICY IF EXISTS "Public MLS remarks are viewable for public properties." ON public.mls_listing_public_remarks;
CREATE POLICY "Public MLS remarks are viewable for public properties."
ON public.mls_listing_public_remarks FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DROP POLICY IF EXISTS "Public MLS financials are viewable for public properties." ON public.mls_listing_financials;
CREATE POLICY "Public MLS financials are viewable for public properties."
ON public.mls_listing_financials FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DROP POLICY IF EXISTS "Public MLS media is viewable for public properties." ON public.mls_listing_media;
CREATE POLICY "Public MLS media is viewable for public properties."
ON public.mls_listing_media FOR SELECT TO anon, authenticated
USING (public.is_public_property(property_id));

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'mls_listing_details',
    'mls_listing_land',
    'mls_listing_schools',
    'mls_listing_rooms',
    'mls_listing_attributes',
    'mls_listing_farm_ranch',
    'mls_listing_structures',
    'mls_listing_public_remarks',
    'mls_listing_private_remarks',
    'mls_listing_financials',
    'mls_listing_contacts',
    'mls_listing_showing',
    'mls_listing_media'
  ]
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Service role manages %s." ON public.%I', table_name, table_name);
    EXECUTE format(
      'CREATE POLICY "Service role manages %s." ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)',
      table_name,
      table_name
    );
  END LOOP;
END $$;
