'use client';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { sellerCaseResultSchema, sellerMilestones, sellerMilestoneLabels, sellerServiceActionSchema, type SellerCaseResult, type SellerServiceAction } from '@/lib/realtor-workspace/sellerServiceContract';
import { SellerWorkspaceNav } from './SellerWorkspaceNav';
import { SellerLeadScheduleDialog } from './SellerLeadScheduleDialog';

const inputClass = 'mt-1 w-full rounded-lg border border-white/20 bg-slate-950 p-3 text-sm';
const buttonClass = 'rounded-lg border border-cyan-300/30 px-4 py-2 text-sm font-semibold text-cyan-100 disabled:opacity-50';
type Draft = { propertyId: string | null; notes: string; documents: Array<{ label: string; url: string }>; checklist: Array<{ id: string; title: string; done: boolean }> };
const emptyDraft: Draft = { propertyId: null, notes: '', documents: [], checklist: [] };
type ActionFields = SellerServiceAction extends infer T ? T extends SellerServiceAction ? Omit<T,'leadId' | 'expectedRevision' | 'requestKey'> : never : never;
export function SellerCaseWorkspace({ leadId }: { leadId: string }) {
  const [data, setData] = useState<SellerCaseResult | null>(null);
  const [draft, setDraft] = useState<Draft>(emptyDraft);
  const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false); const [needsReload, setNeedsReload] = useState(false);
  const [properties, setProperties] = useState<Array<{ id: string; label: string; status: string }>>([]);
  const [propertyError, setPropertyError] = useState('');
  const [emailReviewed,setEmailReviewed]=useState(false);const [publicationReviewed,setPublicationReviewed]=useState(false);
  const [schedule, setSchedule] = useState<{ id: string; startsAt: string } | null>(null);
  const retries = useRef(new Map<string,string>()); const scheduleRetries = useRef(new Map<string,string>());
  const inflight = useRef(false);
  const load = useCallback(async (signal?: AbortSignal) => {
    const response = await fetch(`/api/realtor/seller-service?leadId=${encodeURIComponent(leadId)}`, { cache: 'no-store', signal });
    const body = await response.json();
    if (!response.ok || !body.ok) throw new Error(response.status === 401 ? 'Sign in to open your seller cases.' : body.error || 'Unable to load this case.');
    const value = sellerCaseResultSchema.parse(body.result); if (signal?.aborted) return false;
    setData(value); setDraft(value.case ? { propertyId: value.case.property_id, notes: value.case.notes, documents: value.case.documents, checklist: value.case.checklist } : emptyDraft);
    setNeedsReload(false);setEmailReviewed(false);setPublicationReviewed(false); return true;
  }, [leadId]);
  useEffect(() => {
    const controller = new AbortController();
    void load(controller.signal).catch((reason) => { if (!controller.signal.aborted) setError(reason.message); });
    void fetch('/api/realtor/planner/properties', { cache: 'no-store', signal: controller.signal }).then(async (response) => {
      const body = await response.json(); if (!response.ok || !body.ok) throw new Error(); if (!controller.signal.aborted) setProperties(body.result.properties);
    }).catch(() => { if (!controller.signal.aborted) setPropertyError('Property choices are unavailable. You can keep the existing property and retry after planner setup.'); });
    return () => controller.abort();
  }, [load]);
  const dirty = JSON.stringify(draft) !== JSON.stringify(data?.case ? { propertyId: data.case.property_id, notes: data.case.notes, documents: data.case.documents, checklist: data.case.checklist } : emptyDraft);
  const disabled = busy || needsReload; const otherDisabled = disabled || dirty;
  const act = async (fields: ActionFields) => {
    if (!data || inflight.current || needsReload) return;
    const base = { ...fields, leadId, expectedRevision: data.case?.revision || 1 };
    const fingerprint = JSON.stringify(base); const requestKey = retries.current.get(fingerprint) || crypto.randomUUID(); retries.current.set(fingerprint,requestKey);
    const parsed = sellerServiceActionSchema.safeParse({ ...base, requestKey });
    if (!parsed.success) { setError('Check the form details, document links, and date before saving.'); return; }
    inflight.current = true; setBusy(true); setError(''); setNotice('');
    try {
      const response = await fetch('/api/realtor/seller-service', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(parsed.data) });
      const body = await response.json();
      if (!response.ok || !body.ok) { if (response.status === 409) setNeedsReload(true); throw new Error(body.error || 'Unable to save. Retry the same action.'); }
      await load();
      if (fields.action === 'link_booking' && body.result.details?.consultationEventId) setSchedule({ id: body.result.details.consultationEventId, startsAt: body.result.details.startsAt });
      setNotice(fields.action === 'send_email' ? 'Email queued for the shared worker. Check its receipt below; queueing does not record contact.' : 'Saved.');
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save. Retry the same action.'); }
    finally { inflight.current = false; setBusy(false); }
  };
  const savedMilestones = data?.milestones || [];
  return <main className="min-h-screen bg-slate-950 px-4 py-10 text-white"><div className="mx-auto max-w-6xl space-y-6">
    <SellerWorkspaceNav active="/seller-cases" /><div><p className="text-sm text-cyan-200">Seller case</p><h1 className="mt-1 text-3xl font-bold">{data?.lead.name || 'Seller workspace'}</h1><Link className="mt-2 inline-block text-sm text-cyan-200 underline" href={`/seller-inbox?leadId=${encodeURIComponent(leadId)}`}>Open request, permissions and closing records</Link></div>
    {error ? <p role="alert" className="rounded-xl border border-rose-300/30 p-4">{error} <button className="underline" disabled={busy} onClick={() => { setError(''); void load().catch((reason) => setError(reason.message)); }}>Reload case</button></p> : null}
    {notice ? <p role="status" className="text-cyan-100">{notice}</p> : null}
    {!data && !error ? <p role="status">Loading case…</p> : null}
    {data ? <>
      {dirty ? <p className="text-sm text-amber-200">Save your case changes before recording another action.</p> : null}
      <div className="grid gap-6 lg:grid-cols-2">
        <CasePanel title="Property, preparation and documents"><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); void act({ action:'save_case',...draft }); }}>
          <label className="block text-sm">Property from your shortlist<select disabled={disabled || Boolean(propertyError)} className={inputClass} value={draft.propertyId || ''} onChange={(event) => setDraft({ ...draft,propertyId:event.target.value || null })}><option value="">No property linked</option>{draft.propertyId && !properties.some((p) => p.id === draft.propertyId) ? <option value={draft.propertyId}>Existing linked property</option> : null}{properties.filter((p) => p.status==='active' || p.id===draft.propertyId).map((p) => <option key={p.id} value={p.id}>{p.label}</option>)}</select></label>
          {propertyError ? <p className="text-xs text-amber-200">{propertyError} <Link href="/today" className="underline">Open planner setup</Link></p> : null}
          <label className="block text-sm">Internal notes<textarea className={inputClass} rows={4} maxLength={4000} value={draft.notes} disabled={disabled} onChange={(event) => setDraft({ ...draft,notes:event.target.value })} /></label>
          <fieldset disabled={disabled}><legend className="text-sm font-semibold">Preparation checklist</legend>{draft.checklist.map((item,index) => <div key={item.id} className="mt-2 flex gap-2"><label className="flex flex-1 items-center gap-2"><input type="checkbox" checked={item.done} onChange={(event) => setDraft({ ...draft,checklist:draft.checklist.map((row) => row.id===item.id ? {...row,done:event.target.checked}:row) })} /><input aria-label={`Checklist item ${index+1}`} className={inputClass} required maxLength={160} value={item.title} onChange={(event) => setDraft({ ...draft,checklist:draft.checklist.map((row) => row.id===item.id ? {...row,title:event.target.value}:row) })} /></label><button type="button" aria-label={`Remove checklist item ${index+1}`} onClick={() => setDraft({ ...draft,checklist:draft.checklist.filter((row) => row.id!==item.id) })}>Remove</button></div>)}<button type="button" className="mt-2 text-sm text-cyan-200 underline" disabled={draft.checklist.length>=30} onClick={() => setDraft({...draft,checklist:[...draft.checklist,{id:crypto.randomUUID(),title:'',done:false}]})}>Add checklist item</button></fieldset>
          <fieldset disabled={disabled}><legend className="text-sm font-semibold">Reviewed document links</legend>{draft.documents.map((document,index) => <div key={index} className="mt-2 rounded-lg border border-white/15 p-3"><label className="block text-xs">Document label<input className={inputClass} required maxLength={120} value={document.label} onChange={(event) => setDraft({...draft,documents:draft.documents.map((row,i) => i===index ? {...row,label:event.target.value}:row)})} /></label><label className="block text-xs">HTTPS link<input type="url" className={inputClass} required maxLength={2000} value={document.url} onChange={(event) => setDraft({...draft,documents:draft.documents.map((row,i) => i===index ? {...row,url:event.target.value}:row)})} /></label><button type="button" className="mt-2 text-xs underline" aria-label={`Remove document ${index+1}`} onClick={() => setDraft({...draft,documents:draft.documents.filter((_,i)=>i!==index)})}>Remove document</button></div>)}<button type="button" className="mt-2 text-sm text-cyan-200 underline" disabled={draft.documents.length>=20} onClick={() => setDraft({...draft,documents:[...draft.documents,{label:'',url:''}]})}>Add document link</button></fieldset>
          <button disabled={disabled} className={buttonClass}>Save case</button><Link href="/contracts/representation" className="ml-3 text-sm text-cyan-200 underline">Contracts</Link><Link href="/planner" className="ml-3 text-sm text-cyan-200 underline">Schedule preparation</Link>
        </form></CasePanel>
        <div className="space-y-6"><CasePanel title="Evidence and milestones"><form className="space-y-3" onSubmit={(event) => { event.preventDefault(); const form=new FormData(event.currentTarget); void act({action:'milestone',milestone:form.get('milestone') as typeof sellerMilestones[number],occurredOn:String(form.get('date')),evidence:String(form.get('evidence'))}); }}>
          <label className="block text-sm">Milestone<select name="milestone" className={inputClass} disabled={otherDisabled}>{sellerMilestones.map((value) => <option key={value} value={value}>{sellerMilestoneLabels[value]}</option>)}</select></label>
          <label className="block text-sm">Date in {data.timeZone}<input name="date" type="date" required className={inputClass} disabled={otherDisabled} /></label><label className="block text-sm">Evidence or agreement reference<textarea name="evidence" maxLength={1000} required className={inputClass} disabled={otherDisabled} /></label><button className={buttonClass} disabled={otherDisabled}>Record milestone</button>
          <p className="text-xs text-slate-400">Only record events that happened. Booking is separate from attendance. Verify the listing agreement before recording listing work; record an actual closing in the inbox first.</p>
        </form><div className="mt-4 space-y-3">{data.milestoneRecords.map((record)=><form key={record.eventId} className="rounded-lg border border-white/15 p-3" onSubmit={(event)=>{event.preventDefault();void act({action:'retract_milestone',eventId:record.eventId,reason:String(new FormData(event.currentTarget).get('reason'))});}}><p className="text-sm font-semibold text-cyan-100">{sellerMilestoneLabels[record.milestone]} · {record.occurredOn}</p><p className="mt-1 whitespace-pre-wrap text-xs text-slate-300">{record.evidence}</p><label className="mt-2 block text-xs">Correction reason<input name="reason" required maxLength={1000} disabled={otherDisabled} className={inputClass}/></label><button disabled={otherDisabled} className="mt-2 text-xs text-amber-200 underline">Retract incorrect milestone</button></form>)}<p className="text-xs text-slate-400">Corrections retain the original history, withdraw the milestone from the funnel, and revoke the shared publication until you review it again. Retract dependent listing stages before retracting its agreement.</p></div></CasePanel>
        <CasePanel title="Existing consultation bookings"><p className="mb-3 text-xs text-slate-400">Latest 50 bookings for this request. Link an accepted booking, then save its exact time in the existing planner. Changes or cancellation invalidate its old consultation task.</p>{data.bookings.length ? <ul className="space-y-3">{data.bookings.map((booking) => <li key={booking.id} className="rounded-lg bg-white/5 p-3"><time dateTime={booking.start_time}>{new Date(booking.start_time).toLocaleString(undefined,{timeZone:data.timeZone})}</time><p className="text-xs text-slate-400">{booking.status} · {booking.linked ? 'linked to this case' : 'unlinked'}</p>{!booking.linked && booking.status==='accepted' ? <button disabled={otherDisabled} className={`${buttonClass} mt-2`} onClick={() => void act({action:'link_booking',bookingId:booking.id})}>Link booking and schedule</button>:null}</li>)}</ul> : <p className="text-sm text-slate-400">No existing consultation bookings. Use the seller's existing booking link to request one.</p>}</CasePanel></div>
      </div>
      <div className="grid gap-6 lg:grid-cols-2"><CasePanel title="Conversation and reviewed email"><form className="space-y-3" onChange={(event)=>{if(event.target.getAttribute('name')!=='reviewed')setEmailReviewed(false);}} onSubmit={(event) => { event.preventDefault(); const fields=new FormData(event.currentTarget); const action=String(fields.get('mode')); const subject=String(fields.get('subject')); const body=String(fields.get('body'));
        if (action==='send_email') { if(fields.get('reviewed')!=='on') {setError('Review the recipient and exact email before sending.');return;} void act({action:'send_email',reviewed:true,expectedLeadRevision:data.lead.revision,subject,body}); }
        else void act({action:'record_message',direction:action==='inbound'?'inbound':'outbound',subject,body,occurredAt:String(fields.get('occurredAt'))}); }}>
        <p className="text-sm">Recipient: <strong>{data.lead.email || 'No email recorded'}</strong></p><p className="text-xs text-slate-400">Sender: {data.emailFrom || 'Not configured'}. Replies go to your verified account mailbox.</p>{!data.contactAllowed?<p className="text-xs text-amber-200">This request does not currently allow another email. Review its contact permission and replies in the inbox.</p>:null}<label className="block text-sm">Action<select name="mode" className={inputClass} disabled={otherDisabled}><option value="inbound">Record a received reply</option><option value="outbound">Record an email already sent</option><option value="send_email" disabled={!data.emailEnabled || !data.contactAllowed}>Queue reviewed email</option></select></label>
        <label className="block text-sm">Subject<input name="subject" className={inputClass} required maxLength={200} disabled={otherDisabled}/></label><label className="block text-sm">Message<textarea name="body" rows={5} className={inputClass} required maxLength={8000} disabled={otherDisabled}/></label>
        <label className="block text-sm">For an existing message: exact timestamp with offset<input name="occurredAt" className={inputClass} placeholder="2026-10-09T09:30:00-05:00" disabled={otherDisabled}/></label><label className="flex gap-2 text-sm"><input name="reviewed" type="checkbox" checked={emailReviewed} onChange={(event)=>setEmailReviewed(event.target.checked)} disabled={otherDisabled}/>I reviewed this exact message and recipient before queueing email.</label>
        <button className={buttonClass} disabled={otherDisabled}>Save message action</button><p className="text-xs text-slate-400">Email sending {data.emailEnabled ? 'is configured; the worker rechecks contact permission.' : 'requires configured sender credentials and the send gate in Setup.'} Replies are recorded manually from your verified reply-to mailbox. Accepted means the provider received it; delivered requires a signed delivery receipt. Do not re-send an unknown attempt without checking the provider.</p>
      </form><ul className="mt-5 space-y-3">{data.messages.map((message) => <li key={message.id} className="rounded-lg border border-white/15 p-3"><p className="text-xs text-slate-400">{message.direction} · {message.status} · <time dateTime={message.occurred_at}>{new Date(message.occurred_at).toLocaleString(undefined,{timeZone:data.timeZone})}</time></p><h3 className="mt-1 font-semibold">{message.subject}</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm">{message.body}</p></li>)}</ul>{data.hasMoreMessages ? <p className="mt-3 text-xs text-amber-200">Showing the latest 100 messages.</p>:null}</CasePanel>
      <CasePanel title="Private seller progress"><form key={data.case?.published_at || 'unpublished'} className="space-y-3" onChange={(event)=>{if(event.target.getAttribute('name')!=='reviewed')setPublicationReviewed(false);}} onSubmit={(event) => {event.preventDefault();const form=new FormData(event.currentTarget);if(form.get('reviewed')!=='on'){setError('Review the complete client preview before publishing.');return;}void act({action:'publish_progress',reviewed:true,publication:{summary:String(form.get('summary')),milestones:savedMilestones.filter((m)=>form.get(`milestone:${m}`)==='on'),checklist:(data.case?.checklist||[]).filter((item)=>form.get(`item:${item.id}`)==='on'),documents:(data.case?.documents||[]).filter((_,index)=>form.get(`document:${index}`)==='on')}});}}>
        <p className="text-xs text-slate-400">Only selected saved fields and the summary below are published. Review each document’s access permissions. Internal notes and conversations stay private. Updates require publication again.</p>
        <label className="block text-sm">Client summary<textarea name="summary" maxLength={2000} rows={4} className={inputClass} defaultValue={data.case?.publication?.summary || ''} disabled={otherDisabled}/></label>
        <fieldset disabled={otherDisabled}><legend className="text-sm">Include these milestones</legend>{savedMilestones.map((m)=><label key={m} className="mt-2 flex gap-2 text-sm"><input type="checkbox" name={`milestone:${m}`} defaultChecked={data.case?.publication?.milestones.includes(m)}/>{sellerMilestoneLabels[m]}</label>)}</fieldset>
        <fieldset disabled={otherDisabled}><legend className="text-sm">Include checklist</legend>{data.case?.checklist.map((item)=><label key={item.id} className="mt-2 flex gap-2 text-sm"><input type="checkbox" name={`item:${item.id}`} defaultChecked={data.case?.publication?.checklist.some((row)=>row.id===item.id)}/>{item.done?'✓ ':''}{item.title}</label>)}</fieldset>
        <fieldset disabled={otherDisabled}><legend className="text-sm">Include documents</legend>{data.case?.documents.map((doc,index)=><label key={index} className="mt-2 flex gap-2 text-sm"><input type="checkbox" name={`document:${index}`} defaultChecked={data.case?.publication?.documents.some((row)=>row.url===doc.url && row.label===doc.label)}/><a className="underline" href={doc.url} target="_blank" rel="noopener noreferrer">{doc.label}</a></label>)}</fieldset>
        <label className="flex gap-2 text-sm"><input type="checkbox" name="reviewed" checked={publicationReviewed} onChange={(event)=>setPublicationReviewed(event.target.checked)} disabled={otherDisabled}/>I reviewed the selected client content and document permissions.</label><button className={buttonClass} disabled={otherDisabled}>Publish reviewed progress</button>
      </form><div className="mt-4 space-y-3 border-t border-white/15 pt-4"><p className="text-sm">Client access: {data.case?.sharing_enabled ? 'enabled' : 'disabled'}</p><button disabled={otherDisabled || !data.case?.publication} className={buttonClass} onClick={()=>void act({action:'share_progress',enabled:!data.case?.sharing_enabled})}>{data.case?.sharing_enabled ? 'Revoke client access' : 'Enable verified seller access'}</button><p className="text-xs text-slate-400">The seller signs in at <Link href="/seller-portal" className="underline text-cyan-200">/seller-portal</Link> with a verified account matching {data.lead.email}. No public token or invitation is sent.</p></div></CasePanel></div>
      <CasePanel title="Case history"><ul className="space-y-3">{data.events.map((event)=><li key={event.id} className="rounded-lg bg-white/5 p-3 text-sm"><p>{event.kind.replaceAll('_',' ')} · <time dateTime={event.occurred_at}>{new Date(event.occurred_at).toLocaleString(undefined,{timeZone:data.timeZone})}</time></p>{typeof event.details.reason==='string'?<p className="mt-1 whitespace-pre-wrap text-slate-300">{event.details.reason}</p>:null}{typeof event.details.evidence==='string'?<p className="mt-1 whitespace-pre-wrap text-slate-300">{event.details.evidence}</p>:null}{event.kind==='link_booking' && typeof event.details.consultationEventId==='string' && typeof event.details.startsAt==='string'?<button disabled={otherDisabled} className="mt-2 text-cyan-200 underline" onClick={()=>setSchedule({id:String(event.details.consultationEventId),startsAt:String(event.details.startsAt)})}>Open consultation in planner</button>:null}</li>)}</ul>{data.hasMoreEvents?<p className="mt-3 text-xs text-amber-200">Showing the latest 100 case events.</p>:null}</CasePanel>
      {schedule?<SellerLeadScheduleDialog leadId={leadId} leadName={data.lead.name} leadRevision={data.lead.revision} timeZone={data.timeZone} retryRequests={scheduleRetries.current} actionKey={`consultation:${schedule.id}`} consultationStartsAt={schedule.startsAt} onClose={()=>setSchedule(null)} onReload={()=>load()} onSaved={()=>{setSchedule(null);setNotice('Saved in the existing planner and reminder infrastructure.');void load().catch(()=>setNeedsReload(true));}}/>:null}
    </>:null}
  </div></main>;
}
function CasePanel({ title,children }: { title:string;children:React.ReactNode }) { return <section className="min-w-0 rounded-2xl border border-white/15 bg-slate-900/60 p-5"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>; }
