'use client';
import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { z } from 'zod';
import { sellerPublicationSchema,sellerMilestoneLabels } from '@/lib/realtor-workspace/sellerServiceContract';
const schema=z.array(z.object({leadId:z.string().uuid(),publication:sellerPublicationSchema,publishedAt:z.string()}).strict());
type Progress=z.infer<typeof schema>;
export function SellerPortal() {
  const [rows,setRows]=useState<Progress|null>(null);const [error,setError]=useState('');const [reload,setReload]=useState(0);
  useEffect(()=>{const controller=new AbortController();void fetch('/api/seller-portal',{cache:'no-store',signal:controller.signal}).then(async(response)=>{const body=await response.json();if(!response.ok || !body.ok)throw new Error(response.status===401?'Sign in with your verified seller email to see shared progress.':'Progress is unavailable. Try again.');const value=schema.parse(body.result);if(!controller.signal.aborted)setRows(value);}).catch((reason)=>{if(!controller.signal.aborted)setError(reason.message);});return()=>controller.abort();},[reload]);
  return <main className="min-h-screen bg-slate-950 px-4 py-10 text-white"><div className="mx-auto max-w-3xl space-y-6"><h1 className="text-3xl font-bold">Your seller progress</h1><p className="text-sm text-slate-300">Reviewed updates and documents shared by your real estate professional.</p>{error?<p role="alert">{error} <Link href="/login?redirect=/seller-portal" className="text-cyan-200 underline">Sign in</Link></p>:rows===null?<p role="status">Loading progress…</p>:!rows.length?<p>No progress is shared with this verified account yet. Ask your real estate professional to publish your update and enable access for your current email.</p>:rows.map((row)=><section key={row.leadId} className="rounded-2xl border border-white/15 p-5"><p className="text-xs text-slate-400">Published <time dateTime={row.publishedAt}>{new Date(row.publishedAt).toLocaleString()}</time></p><h2 className="mt-3 text-xl font-semibold">Sale progress</h2><p className="mt-3 whitespace-pre-wrap break-words">{row.publication.summary}</p><h3 className="mt-5 font-semibold">Completed milestones</h3><ul className="mt-2 space-y-2">{row.publication.milestones.map((milestone)=><li key={milestone}>✓ {sellerMilestoneLabels[milestone]}</li>)}</ul><h3 className="mt-5 font-semibold">Preparation checklist</h3><ul className="mt-2 space-y-2">{row.publication.checklist.map((item)=><li key={item.id}>{item.done?'✓':'○'} {item.title}</li>)}</ul><h3 className="mt-5 font-semibold">Shared documents</h3><ul className="mt-2 space-y-2">{row.publication.documents.map((document,index)=><li key={index}><a className="break-words text-cyan-200 underline" href={document.url} target="_blank" rel="noopener noreferrer">{document.label}</a></li>)}</ul></section>)}<button className="text-cyan-200 underline" onClick={()=>{setRows(null);setError('');setReload((value)=>value+1);}}>Refresh progress</button></div></main>;
}
