'use client';
import React,{useEffect,useState} from 'react';
import Link from 'next/link';
import {sellerOverviewSchema,type SellerOverview} from '@/lib/realtor-workspace/sellerOverviewContract';
export function SellerOverviewPanel({mode='funnel'}:{mode?:'setup'|'funnel'}){
  const [data,setData]=useState<SellerOverview|null>(null);const [error,setError]=useState('');const [reload,setReload]=useState(0);
  useEffect(()=>{const controller=new AbortController();void fetch('/api/realtor/seller-service/overview',{cache:'no-store',signal:controller.signal}).then(async(response)=>{const body=await response.json();if(!response.ok || !body.ok)throw new Error(response.status===401?'Sign in to check your seller setup.':body.error || 'Seller measurements are unavailable.');const value=sellerOverviewSchema.parse(body.result);if(!controller.signal.aborted)setData(value);}).catch((reason)=>{if(!controller.signal.aborted)setError(reason.message);});return()=>controller.abort();},[reload]);
  const retry=<button className="mt-3 text-sm text-cyan-200 underline" onClick={()=>{setData(null);setError('');setReload((value)=>value+1);}}>Refresh seller status</button>;
  if(error)return <section className="rounded-2xl border border-rose-300/30 p-5"><p role="alert">{error}</p><Link href="/login?redirect=/seller-setup" className="mr-4 text-cyan-200 underline">Sign in</Link>{retry}</section>;
  if(!data)return <p role="status" className="p-5 text-sm text-slate-400">Loading seller {mode==='setup'?'setup and worker status':'funnel'}…</p>;
  const health=data.health;const funnel=data.funnel;
  if(mode==='setup')return <div className="space-y-6"><section className="rounded-2xl border border-white/15 p-5"><h2 className="text-xl font-semibold">Set up your daily seller workflow</h2><ol className="mt-4 space-y-4">
    <li><strong>1. Personal planner and timezone</strong><p className="mt-1 text-sm text-slate-300">{health.plannerConfigured?`Configured in ${health.timeZone}.`:'Set up your personal planner before scheduling seller actions.'} Reminders {health.remindersEnabled?'enabled':'disabled'}.</p><Link className="text-sm text-cyan-200 underline" href="/today">Open planner setup and Today</Link></li>
    <li><strong>2. Active seller website and intake</strong><p className="mt-1 text-sm text-slate-300">{health.activeSites} active owned {health.activeSites===1?'website':'websites'}. Runtime seller intake {health.intakeConfigured?'configured':'not configured'}. Publish the intended website and connect its configured intake. Use your provisioned site setup link or website administration to complete publication.</p><Link className="text-sm text-cyan-200 underline" href="/seller-plan">Open the seller request form</Link></li>
    <li><strong>3. Verify a real request</strong><p className="mt-1 text-sm text-slate-300">Submit an inquiry you intend to keep through the normal seller form; then check the inbox and its requested-contact permission. Latest owned request: {health.lastRequest?new Date(health.lastRequest).toLocaleString():'none recorded'}.</p><Link className="text-sm text-cyan-200 underline" href="/seller-inbox">Check your inbox</Link></li>
    <li><strong>4. Link a booking and schedule work</strong><p className="mt-1 text-sm text-slate-300">Open a case, link an accepted consultation booking, and save its appointment or response task in the existing planner. Record attendance only afterward.</p><Link className="text-sm text-cyan-200 underline" href="/seller-cases">Open cases</Link></li>
    <li><strong>5. Reviewed email and delivery</strong><p className="mt-1 text-sm text-slate-300">Sender configuration: {health.emailConfigured?'enabled':'not enabled'}. Durable email contract: {health.emailContractEnabled?'enabled':'unavailable'}. Delivery webhook: {health.webhookConfigured?'configured':'not configured'}. Email stays unavailable until its dedicated sender gate and credentials are configured; reply capture uses your verified mailbox.</p></li>
    <li><strong>6. Publish private client progress</strong><p className="mt-1 text-sm text-slate-300">Review and publish selected case fields, then enable access for the seller’s verified email. Revoke access from the same case when needed.</p><Link className="text-sm text-cyan-200 underline" href="/seller-portal">Open client sign-in view</Link></li>
  </ol></section><section className="rounded-2xl border border-white/15 p-5"><h2 className="text-xl font-semibold">Recorded worker activity</h2><dl className="mt-4 grid grid-cols-2 gap-4"><Stat label="Pending jobs" value={health.pendingJobs}/><Stat label="Failed jobs" value={health.failedJobs}/><Stat label="Emails needing review" value={health.unresolvedEmails}/><div><dt className="text-xs text-slate-400">Latest completed job</dt><dd className="mt-1 text-sm">{health.lastCompletedJob?new Date(health.lastCompletedJob).toLocaleString():'No completion recorded'}</dd></div></dl><p className="mt-4 text-xs text-slate-400">These are your stored job records and this app’s configuration. A configured sender or a prior completed job does not prove the currently deployed cron is running. Failed jobs and unknown email attempts need operator review; check provider receipts before any resend.</p>{retry}</section></div>;
  return <section className="rounded-2xl border border-cyan-300/20 bg-slate-900/60 p-5"><h2 className="text-xl font-semibold">Seller acquisition funnel</h2><p className="mt-2 text-xs text-slate-400">Requests created from {new Date(funnel.startAt).toLocaleDateString(undefined,{timeZone:funnel.timeZone})} through now · {funnel.timeZone}. Outcomes follow those same requests through today.</p><dl className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="Opted-in visits" value={funnel.visits}/><Stat label="Request-button actions" value={funnel.offerClicks}/><Stat label="Requests" value={funnel.requests}/><Stat label="Replied" value={funnel.replies}/><Stat label="Consultations held" value={funnel.held}/><Stat label="Agreements verified" value={funnel.signed}/><Stat label="Recorded closings" value={funnel.closed}/><Stat label="Request → agreement" value={funnel.requests?`${Math.round(funnel.signed/funnel.requests*100)}%`:'—'}/></dl><p className="mt-4 text-xs text-slate-400">Visits and button actions include only visitors who opt in on the seller offer and are independent observations. They are not a denominator for all requests. Booking is separate from attendance. Agreement counts require human verification; campaign labels do not establish causation.</p>
    {funnel.campaigns.length?<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><caption className="mb-2 text-left font-semibold">Request cohort by campaign</caption><thead><tr>{['Campaign','Requests','Replies','Held','Agreements','Closings'].map((label)=><th scope="col" key={label} className="px-2 py-2">{label}</th>)}</tr></thead><tbody>{funnel.campaigns.map((row)=><tr key={row.campaign} className="border-t border-white/10"><th scope="row" className="max-w-xs break-words px-2 py-2 font-normal">{row.campaign}</th><td className="px-2">{row.requests}</td><td className="px-2">{row.replies}</td><td className="px-2">{row.held}</td><td className="px-2">{row.signed}</td><td className="px-2">{row.closed}</td></tr>)}</tbody></table>{funnel.hasMoreCampaigns?<p className="mt-2 text-xs text-slate-400">Showing the first 50 campaign groups.</p>:null}</div>:<p className="mt-3 text-sm text-slate-400">No requests in this cohort yet.</p>}{retry}</section>;
}
function Stat({label,value}:{label:string;value:number|string}){return <div className="rounded-xl bg-white/5 p-3"><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 text-xl font-bold">{value}</dd></div>;}
