'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Target, TrendingUp, AlertTriangle, Zap, RotateCcw } from 'lucide-react';
// We will import the JSON data generated by Pandas
import productData from '@/lib/data/product_popularity.json';

type Product = {
  id: string;
  name: string;
  category: string;
  monthly_sales: number;
};

export default function RetailClashGame() {
  const [deck, setDeck] = useState<Product[]>([]);
  const [leftItem, setLeftItem] = useState<Product | null>(null);
  const [rightItem, setRightItem] = useState<Product | null>(null);
  const [streak, setStreak] = useState(0);
  const [highScore, setHighScore] = useState(0);
  const [gameState, setGameState] = useState<'playing' | 'revealed' | 'gameover'>('playing');

  // Initialize deck
  useEffect(() => {
    if (productData && productData.length >= 2) {
      // Shuffle the data
      const shuffled = [...productData].sort(() => 0.5 - Math.random()) as Product[];
      setLeftItem(shuffled[0]);
      setRightItem(shuffled[1]);
      setDeck(shuffled.slice(2));
      
      const saved = localStorage.getItem('retailClashHighscore');
      if (saved) setHighScore(parseInt(saved, 10));
    }
  }, []);

  const handleChoice = (chosenSide: 'left' | 'right') => {
    if (gameState !== 'playing' || !leftItem || !rightItem) return;

    const chosenItem = chosenSide === 'left' ? leftItem : rightItem;
    const otherItem = chosenSide === 'left' ? rightItem : leftItem;

    setGameState('revealed');

    if (chosenItem.monthly_sales >= otherItem.monthly_sales) {
      // Correct!
      const newStreak = streak + 1;
      setStreak(newStreak);
      if (newStreak > highScore) {
        setHighScore(newStreak);
        localStorage.setItem('retailClashHighscore', newStreak.toString());
      }

      setTimeout(() => {
        // Move right item to left, pull new right item
        setLeftItem(rightItem);
        if (deck.length > 0) {
          setRightItem(deck[0]);
          setDeck(deck.slice(1));
        } else {
          // Reshuffle if empty
          const reshuffled = [...productData].sort(() => 0.5 - Math.random()) as Product[];
          setRightItem(reshuffled[0]);
          setDeck(reshuffled.slice(1));
        }
        setGameState('playing');
      }, 2000);
    } else {
      // Incorrect
      setTimeout(() => {
        setGameState('gameover');
      }, 2000);
    }
  };

  const restartGame = () => {
    const shuffled = [...productData].sort(() => 0.5 - Math.random()) as Product[];
    setLeftItem(shuffled[0]);
    setRightItem(shuffled[1]);
    setDeck(shuffled.slice(2));
    setStreak(0);
    setGameState('playing');
  };

  if (!leftItem || !rightItem) {
    return <div className="text-white">Loading data...</div>;
  }

  return (
    <div className="w-full max-w-5xl flex flex-col gap-6">
      <div className="flex justify-between items-center bg-[#0d1f2d] p-4 rounded-xl border border-gray-800 shadow-xl">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-orange-500/20 rounded-lg">
            <Zap className="w-5 h-5 text-orange-400" />
          </div>
          <div>
            <div className="text-sm text-gray-400 font-medium tracking-wider">STREAK</div>
            <div className="text-2xl font-bold text-white leading-none">{streak}</div>
          </div>
        </div>
        
        <div className="flex items-center gap-3 text-right">
          <div>
            <div className="text-sm text-gray-400 font-medium tracking-wider">HIGH SCORE</div>
            <div className="text-2xl font-bold text-gray-200 leading-none">{highScore}</div>
          </div>
          <div className="p-2 bg-slate-800 rounded-lg">
            <Target className="w-5 h-5 text-gray-400" />
          </div>
        </div>
      </div>

      <div className="relative grid grid-cols-1 md:grid-cols-2 gap-4 h-[500px]">
        {/* VS Badge */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-10 hidden md:flex items-center justify-center w-16 h-16 rounded-full bg-[#06131d] border-4 border-[#0d1f2d] shadow-2xl">
          <span className="font-black text-xl text-gray-300 italic">VS</span>
        </div>

        {/* Left Item */}
        <div className="relative rounded-2xl overflow-hidden bg-gradient-to-br from-slate-800 to-[#0d1f2d] border border-gray-700 shadow-xl flex flex-col justify-center items-center p-8 group">
          <div className="absolute top-4 left-4 px-3 py-1 bg-black/40 rounded text-xs font-bold text-gray-300 tracking-wider uppercase">
            {leftItem.category}
          </div>
          <h2 className="text-4xl md:text-5xl font-black text-white text-center mb-8 drop-shadow-lg">
            "{leftItem.name}"
          </h2>
          
          <div className="flex flex-col items-center">
            <div className="text-sm text-orange-400 font-semibold tracking-widest mb-2 uppercase">Monthly Volume</div>
            <div className="text-5xl md:text-6xl font-black text-white drop-shadow-[0_0_15px_rgba(255,255,255,0.3)]">
              {leftItem.monthly_sales.toLocaleString()}
            </div>
            <div className="text-gray-400 mt-2">Units / Month</div>
          </div>
        </div>

        {/* Right Item */}
        <div className="relative rounded-2xl overflow-hidden bg-gradient-to-br from-slate-800 to-[#0d1f2d] border border-gray-700 shadow-xl flex flex-col justify-center items-center p-8">
          <div className="absolute top-4 right-4 px-3 py-1 bg-black/40 rounded text-xs font-bold text-gray-300 tracking-wider uppercase">
            {rightItem.category}
          </div>
          <h2 className="text-4xl md:text-5xl font-black text-white text-center mb-8 drop-shadow-lg">
            "{rightItem.name}"
          </h2>
          
          <div className="flex flex-col items-center w-full">
            <div className="text-sm text-gray-400 font-semibold tracking-widest mb-6 uppercase text-center">Has</div>
            
            {gameState === 'playing' ? (
              <div className="flex flex-col gap-4 w-full max-w-xs">
                <button 
                  onClick={() => handleChoice('right')}
                  className="w-full py-4 rounded-xl font-bold text-xl transition-all duration-200 transform hover:scale-105 active:scale-95 bg-white text-black hover:bg-gray-100 flex items-center justify-center gap-2"
                >
                  <TrendingUp className="w-6 h-6" /> HIGHER
                </button>
                <button 
                  onClick={() => handleChoice('left')}
                  className="w-full py-4 rounded-xl font-bold text-xl transition-all duration-200 transform hover:scale-105 active:scale-95 border-2 border-white text-white hover:bg-white/10 flex items-center justify-center gap-2"
                >
                  <TrendingUp className="w-6 h-6 rotate-180" /> LOWER
                </button>
                <div className="text-gray-500 text-center mt-2 text-sm">volume than {leftItem.name}</div>
              </div>
            ) : (
              <AnimatePresence>
                <motion.div 
                  initial={{ scale: 0.5, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  className="flex flex-col items-center"
                >
                  <div className={`text-5xl md:text-6xl font-black ${
                    gameState === 'revealed' && rightItem.monthly_sales >= leftItem.monthly_sales && streak > 0 ? 'text-green-400' :
                    gameState === 'revealed' && rightItem.monthly_sales < leftItem.monthly_sales && streak === 0 ? 'text-red-400' :
                    gameState === 'gameover' ? 'text-red-500' : 'text-white'
                  } drop-shadow-[0_0_15px_rgba(255,255,255,0.3)]`}>
                    {rightItem.monthly_sales.toLocaleString()}
                  </div>
                  <div className="text-gray-400 mt-2">Units / Month</div>
                </motion.div>
              </AnimatePresence>
            )}
          </div>
        </div>
      </div>

      <AnimatePresence>
        {gameState === 'gameover' && (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex flex-col items-center justify-center p-8 bg-red-950/40 border border-red-900/50 rounded-2xl shadow-2xl mt-4"
          >
            <AlertTriangle className="w-12 h-12 text-red-500 mb-4" />
            <h3 className="text-3xl font-black text-white mb-2">STREAK BROKEN</h3>
            <p className="text-red-200 mb-6 text-center max-w-md">
              "{rightItem.name}" actually moves {rightItem.monthly_sales.toLocaleString()} units, compared to {leftItem.monthly_sales.toLocaleString()} for "{leftItem.name}".
            </p>
            <button 
              onClick={restartGame}
              className="px-8 py-4 bg-white text-red-950 font-black rounded-xl hover:bg-gray-100 transition-colors flex items-center gap-2 text-lg"
            >
              <RotateCcw className="w-5 h-5" /> TRY AGAIN
            </button>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
