import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
vi.mock('next/navigation', () => ({ useRouter: () => ({ push: vi.fn() }), useSearchParams: () => new URLSearchParams('siteId=site-a') }));
import { ThemeDirectory } from '@/app/vibes/appearance/ThemeDirectory';
describe('CMS Appearance themes', () => { afterEach(() => vi.unstubAllGlobals());
  it('shows effective theme state and explicitly activates another catalog entry', async () => { const theme = { id: 'sunset/core', name: 'Sunset Core', version: '1.0.0', description: 'Built in.', author: 'Sunset Pulse', templates: { page: 'sunset/page' }, supportedBlocks: [] }; vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, text: async () => JSON.stringify({ themes: [theme], activeThemeId: 'sunset/core' }) })); render(<ThemeDirectory />); expect(await screen.findByText('Active')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Active theme' })).toBeDisabled(); });
  it('persists an inactive theme selection', async () => { const themes = [{ id: 'sunset/core', name: 'Sunset Core', version: '1.0.0', description: 'Built in.', author: 'Sunset Pulse', templates: {}, supportedBlocks: [] }, { id: 'sunset/editorial', name: 'Editorial', version: '1.0.0', description: 'Editorial.', author: 'Sunset Pulse', templates: {}, supportedBlocks: [] }]; const fetchMock = vi.fn().mockResolvedValueOnce({ ok: true, text: async () => JSON.stringify({ themes, activeThemeId: 'sunset/core' }) }).mockResolvedValueOnce({ ok: true, text: async () => JSON.stringify({ activation: { themeId: 'sunset/editorial' } }) }); vi.stubGlobal('fetch', fetchMock); render(<ThemeDirectory />); fireEvent.click(await screen.findByRole('button', { name: 'Activate' })); await waitFor(() => expect(screen.getAllByText('Active').length).toBeGreaterThan(0)); expect(fetchMock).toHaveBeenLastCalledWith('/api/vibes/themes?siteId=site-a', expect.objectContaining({ method: 'POST', body: JSON.stringify({ themeId: 'sunset/editorial' }) })); });
});
