'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';

export default function PublishVibePage() {
  const { vibeId } = useParams<{ vibeId: string }>(); const router = useRouter();
  const [vibe, setVibe] = useState<any>(null); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [publishing, setPublishing] = useState(false);
  useEffect(() => { fetch(`/api/admin/vibes/${encodeURIComponent(vibeId)}`).then((response) => response.json()).then((payload) => setVibe(payload.vibe)).catch(() => setError('Unable to load vibe.')); }, [vibeId]);
  async function publish() { setPublishing(true); setError(''); const response = await fetch(`/api/admin/vibes/${encodeURIComponent(vibeId)}/publish`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ draft: vibe.draftPayload, changeSummary: reason }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error || 'Publication failed.'); setPublishing(false); return; } router.push(`/admin/vibes/${encodeURIComponent(vibeId)}/revisions`); }
  if (!vibe) return <main className="min-h-screen bg-slate-100 p-8 text-slate-500">Loading publication review…</main>;
  return <main className="min-h-screen bg-slate-100 px-4 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-2xl"><Link href={`/admin/vibes/${vibeId}/edit`} className="text-sm font-semibold text-slate-500 hover:underline">← Back to editor</Link><h1 className="mt-4 text-3xl font-black">Publish vibe</h1><p className="mt-1 text-sm text-slate-600">Create an immutable published revision for <strong>{vibe.title || vibe.name || vibe.vibeId}</strong>.</p><section className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><strong>Review carefully.</strong> Publishing freezes the current normalized draft. Later edits will not change this revision or any site using it.</section><form className="mt-5 space-y-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm" onSubmit={(event) => { event.preventDefault(); void publish(); }}><label className="block text-sm font-bold">Change summary<span className="ml-1 font-normal text-slate-500">(optional)</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Describe what is changing in this revision" className="mt-2 min-h-28 w-full rounded-md border border-slate-300 px-3 py-2 font-normal" /></label>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={publishing || !vibe.draftPayload} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{publishing ? 'Publishing…' : 'Publish immutable revision'}</button></form></div></main>;
}
