'use client';
import Link from 'next/link'; import { useRouter } from 'next/navigation'; import { useState } from 'react';
const PRESETS = [{ id: '', name: 'Default', note: 'A neutral, editable starting point.', colors: ['#2563eb', '#0f172a', '#f8fafc'] }, { id: 'editorial', name: 'Editorial warmth', note: 'Warm, considered visual language.', colors: ['#7c2d12', '#fff7ed', '#431407'] }, { id: 'market-intelligence', name: 'Market intelligence', note: 'Calm, analytical market presentation.', colors: ['#0f766e', '#f0fdfa', '#134e4a'] }] as const;
function toSlug(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''); }
export default function NewVibePage() {
  const router = useRouter(); const [title, setTitle] = useState(''); const [slug, setSlug] = useState(''); const [slugEdited, setSlugEdited] = useState(false); const [description, setDescription] = useState(''); const [preset, setPreset] = useState<string>(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function create() { setSaving(true); setError(''); const response = await fetch('/api/vibes', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ title, slug, description, ...(preset ? { preset } : {}) }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error || 'Unable to create vibe.'); setSaving(false); return; } router.push(`/vibes/${payload.vibe.vibeId}/edit`); }
  return <main className="min-h-screen bg-slate-100 px-4 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-2xl"><Link href="/vibes" className="text-sm font-semibold text-slate-500 hover:underline">← All Vibes</Link><h1 className="mt-4 text-3xl font-black">Add New Vibe</h1><p className="mt-1 text-sm text-slate-600">Create a draft identity to continue in the structured editor.</p><form className="mt-6 space-y-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm" onSubmit={(event) => { event.preventDefault(); void create(); }}><fieldset><legend className="text-sm font-bold">Starting style</legend><p className="mt-1 text-xs text-slate-500">Copied into this new draft only; every value remains editable.</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{PRESETS.map((item) => <label key={item.id || 'default'} className={`cursor-pointer rounded-lg border p-3 ${preset === item.id ? 'border-[#2271b1] bg-sky-50 ring-1 ring-[#2271b1]' : 'border-slate-200 bg-white'}`}><input className="sr-only" type="radio" name="preset" value={item.id} checked={preset === item.id} onChange={() => setPreset(item.id)} /><span className="font-semibold">{item.name}</span><span className="mt-1 block text-xs text-slate-500">{item.note}</span><span className="mt-3 flex overflow-hidden rounded"><i className="h-4 flex-1" style={{ background: item.colors[0] }} /><i className="h-4 flex-1" style={{ background: item.colors[1] }} /><i className="h-4 flex-1" style={{ background: item.colors[2] }} /></span></label>)}</div></fieldset><label className="block text-sm font-bold">Title<input required value={title} onChange={(event) => { const next = event.target.value; setTitle(next); if (!slugEdited) setSlug(toSlug(next)); }} className="mt-2 w-full rounded-md border border-slate-300 px-3 py-2 font-normal" /></label><label className="block text-sm font-bold">Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={(event) => { setSlug(event.target.value); setSlugEdited(event.target.value.length > 0); }} className="mt-2 w-full rounded-md border border-slate-300 px-3 py-2 font-mono font-normal" /></label><label className="block text-sm font-bold">Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} className="mt-2 min-h-32 w-full rounded-md border border-slate-300 px-3 py-2 font-normal" /></label>{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}<button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? 'Creating…' : 'Create Draft'}</button></form></div></main>;
}
