import { z } from 'zod';

export const WebhookTriggerEventsSchema = z.enum(['BOOKING_CREATED','BOOKING_PAYMENT_INITIATED','BOOKING_PAID','BOOKING_RESCHEDULED','BOOKING_REQUESTED','BOOKING_CANCELLED','BOOKING_REJECTED','BOOKING_NO_SHOW_UPDATED','FORM_SUBMITTED','MEETING_ENDED','MEETING_STARTED','RECORDING_READY','RECORDING_TRANSCRIPTION_GENERATED','OOO_CREATED','AFTER_HOSTS_CAL_VIDEO_NO_SHOW','AFTER_GUESTS_CAL_VIDEO_NO_SHOW','FORM_SUBMITTED_NO_EVENT','DELEGATION_CREDENTIAL_ERROR','WRONG_ASSIGNMENT_REPORT']);

export type WebhookTriggerEventsType = `${z.infer<typeof WebhookTriggerEventsSchema>}`

export default WebhookTriggerEventsSchema;
