'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Vibe = { vibeId: string; title?: string; name?: string; slug?: string; status?: string; description?: string; longDescription?: string; publishedRevisionId?: string; currentDraftVersion?: number; updatedAt?: string };

export function VibeEditor({ vibeId }: { vibeId: string }) {
  const [vibe, setVibe] = useState<Vibe | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { fetch(`/api/admin/vibes/${encodeURIComponent(vibeId)}`).then(async (response) => { if (!response.ok) throw new Error('Unable to load vibe.'); return response.json(); }).then((payload) => setVibe(payload.vibe)).catch((reason) => setError(reason.message)); }, [vibeId]);
  if (error) return <main className="min-h-screen bg-slate-100 p-8"><p role="alert" className="text-red-700">{error}</p></main>;
  if (!vibe) return <main className="min-h-screen bg-slate-100 p-8 text-slate-500">Loading vibe…</main>;
  return <main className="min-h-screen bg-slate-100 px-4 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><Link href="/admin/vibes" className="text-sm font-semibold text-slate-500 hover:underline">← All vibes</Link><h1 className="mt-3 text-3xl font-black">{vibe.title || vibe.name || vibe.vibeId}</h1><p className="mt-1 text-sm text-slate-500">/{vibe.slug || vibe.vibeId}</p></div><div className="flex gap-2"><Link href={`/admin/vibes/${vibeId}/revisions`} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-bold">Revision history</Link><button className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white" disabled>Save draft</button></div></div><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><section className="space-y-5"><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-black uppercase tracking-wide text-slate-500">Metadata</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase text-slate-400">Title</dt><dd className="mt-1 font-semibold">{vibe.title || vibe.name || 'Untitled'}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Slug</dt><dd className="mt-1 font-mono text-sm">{vibe.slug || 'Not assigned'}</dd></div><div className="sm:col-span-2"><dt className="text-xs font-bold uppercase text-slate-400">Description</dt><dd className="mt-1 text-sm text-slate-700">{vibe.longDescription || vibe.description || 'No description yet.'}</dd></div></dl></article><article className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5"><h2 className="text-sm font-black uppercase tracking-wide text-slate-500">Structured token editors</h2><p className="mt-2 text-sm text-slate-600">Visual theme, effects, voice, taxonomy, and source fields will appear here as structured controls. Legacy data remains readable while it is normalized.</p></article></section><aside className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-black uppercase tracking-wide text-slate-500">Editorial status</h2><p className="mt-3 inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{vibe.status || 'draft'}</p><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-slate-500">Draft version</dt><dd className="font-semibold">{vibe.currentDraftVersion ?? 0}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Published revision</dt><dd className="font-semibold">{vibe.publishedRevisionId ? 'Assigned' : 'None'}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Last modified</dt><dd className="font-semibold">{vibe.updatedAt ? new Date(vibe.updatedAt).toLocaleDateString() : '—'}</dd></div></dl></aside></div></div></main>;
}
