/**
 * Workflow / Sprint Schema for Sunset Pulse
 * Defines the structured JSON roadmap generated by Jamie.
 */
export const WorkflowSchema = {
  sprint_name: "String (e.g., 'Lead Reactivation - John Doe')",
  total_duration_hours: "Number",
  tasks: [
    {
      task_id: "String (UUID/ShortID)",
      title: "String",
      description: "String",
      duration_minutes: "Number",
      api_endpoint: "String (Internal or External URL)",
      priority: "String (Low/Medium/High/Critical)",
      status: "String (Pending/Active/Complete)"
    }
  ],
  business_goal: "String",
  metadata: {
    lead_id: "String",
    agent_id: "String",
    urgency_score: "Number"
  }
};

export default WorkflowSchema;
