'use client';

import { useCallback, useEffect, useState } from 'react';
import { Archive, CheckCircle2, Clipboard, Loader2, Printer, Save, Settings2 } from 'lucide-react';

type LeadRef = { name: string | null; first_name: string | null; last_name: string | null; property_address: string | null; mailing_address: string | null; do_not_contact: boolean };
type Draft = { id: string; lead_id: string; channel: 'email' | 'letter'; recipient_email: string | null; subject: string | null; body: string; status: 'draft' | 'approved' | 'archived'; created_by_name: string | null; updated_by_name: string | null; updated_at: string; approved_at: string | null; leads: LeadRef | LeadRef[] | null };
type Settings = { agent_name?: string; brokerage_name?: string; phone?: string; email?: string; license_number?: string; signature?: string };

export default function LeadDraftWorkspace() {
  const [drafts, setDrafts] = useState<Draft[]>([]); const [selected, setSelected] = useState<Draft | null>(null);
  const [subject, setSubject] = useState(''); const [body, setBody] = useState(''); const [settings, setSettings] = useState<Settings>({});
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [showSettings, setShowSettings] = useState(false);
  const load = useCallback(async () => { setLoading(true); const response = await fetch('/api/admin/leads/correspondence', { cache: 'no-store' }); const payload = await response.json().catch(() => ({})); if (response.ok) { setDrafts(payload.drafts || []); setSettings(payload.settings || {}); } else setMessage(payload.error || 'Drafts unavailable.'); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const choose = (draft: Draft) => { setSelected(draft); setSubject(draft.subject || ''); setBody(draft.body); setMessage(''); };
  const patch = async (payload: Record<string, unknown>) => { setBusy(true); setMessage(''); const response = await fetch('/api/admin/leads/correspondence', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(result.error || 'Update failed.'); return false; } await load(); return true; };
  const leadFor = (draft: Draft) => Array.isArray(draft.leads) ? draft.leads[0] : draft.leads;
  const printDraft = () => { if (!selected) return; const lead = leadFor(selected); const popup = window.open('', '_blank', 'noopener,noreferrer'); if (!popup) return setMessage('Allow popups to print this letter.'); popup.document.write(`<title>Letter - ${escapeHtml(lead?.property_address || '')}</title><style>body{font:16px Georgia,serif;line-height:1.65;max-width:720px;margin:60px auto;padding:0 30px;white-space:pre-wrap;color:#111}@media print{body{margin:0 auto}}</style>${escapeHtml(body)}`); popup.document.close(); popup.print(); };
  if (loading) return <div className="flex min-h-64 items-center justify-center"><Loader2 className="animate-spin text-cyan-200" /></div>;
  return <div className="grid gap-6 lg:grid-cols-[360px_minmax(0,1fr)]">
    <aside className="border border-white/10 bg-white/[0.025]"><div className="flex items-center justify-between border-b border-white/10 p-4"><div><h2 className="font-black text-white">Shared queue</h2><p className="mt-1 text-xs text-zinc-500">{drafts.filter((draft) => draft.status === 'draft').length} awaiting review</p></div><button type="button" onClick={() => setShowSettings((value) => !value)} className="flex h-9 w-9 items-center justify-center border border-white/10 text-zinc-300" title="Agent identity"><Settings2 size={16} /></button></div>
      <div className="max-h-[70vh] divide-y divide-white/10 overflow-y-auto">{drafts.map((draft) => { const lead = leadFor(draft); return <button key={draft.id} type="button" onClick={() => choose(draft)} className={`block w-full px-4 py-4 text-left ${selected?.id === draft.id ? 'bg-cyan-300/10' : 'hover:bg-white/[0.04]'}`}><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-bold text-white">{[lead?.first_name, lead?.last_name].filter(Boolean).join(' ') || lead?.name || 'Lead'}</p><span className={`text-[9px] font-black uppercase ${draft.status === 'approved' ? 'text-emerald-200' : draft.status === 'archived' ? 'text-zinc-600' : 'text-amber-200'}`}>{draft.status}</span></div><p className="mt-1 truncate text-xs text-zinc-500">{lead?.property_address || draft.recipient_email || draft.channel}</p><p className="mt-2 text-[10px] text-zinc-600">Updated by {draft.updated_by_name || draft.created_by_name || 'Operator'}</p></button>; })}</div>
    </aside>
    <section className="min-w-0 border border-white/10 bg-white/[0.025]">
      {showSettings ? <IdentitySettings settings={settings} setSettings={setSettings} busy={busy} onSave={() => void patch({ action: 'save_settings', agentName: settings.agent_name || '', brokerageName: settings.brokerage_name || '', phone: settings.phone || '', email: settings.email || '', licenseNumber: settings.license_number || '', signature: settings.signature || '' })} /> : null}
      {!selected ? <div className="flex min-h-[480px] items-center justify-center p-8 text-sm text-zinc-500">Select a draft to review.</div> : <div className="p-5"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-cyan-200">{selected.channel}</p><h2 className="mt-1 text-lg font-black text-white">{leadFor(selected)?.property_address || 'Lead correspondence'}</h2>{leadFor(selected)?.do_not_contact ? <p className="mt-2 text-xs font-bold text-rose-200">Do not contact restriction active</p> : null}</div><div className="flex gap-2"><button type="button" onClick={() => void navigator.clipboard.writeText(body)} className="icon-button" title="Copy draft"><Clipboard size={16} /></button><button type="button" onClick={printDraft} className="icon-button" title="Print letter"><Printer size={16} /></button></div></div>
        {selected.channel === 'email' ? <label className="block text-xs font-bold text-zinc-300">Subject<input value={subject} disabled={selected.status !== 'draft'} onChange={(event) => setSubject(event.target.value)} className="mt-2 w-full border border-white/10 bg-black/25 px-3 py-2 text-sm text-white" /></label> : null}
        <label className="mt-4 block text-xs font-bold text-zinc-300">Body<textarea value={body} disabled={selected.status !== 'draft'} onChange={(event) => setBody(event.target.value)} rows={18} className="mt-2 w-full resize-y border border-white/10 bg-black/25 px-4 py-3 text-sm leading-6 text-white" /></label>
        {message ? <p className="mt-3 text-sm text-amber-100">{message}</p> : null}<div className="mt-5 flex flex-wrap gap-3">{selected.status === 'draft' ? <><button disabled={busy} type="button" onClick={() => void patch({ action: 'update_draft', id: selected.id, subject: selected.channel === 'email' ? subject : null, body })} className="action-secondary"><Save size={15} />Save</button><button disabled={busy || leadFor(selected)?.do_not_contact} type="button" onClick={() => void patch({ action: 'set_status', id: selected.id, status: 'approved' })} className="action-primary"><CheckCircle2 size={15} />Approve & schedule</button></> : null}<button disabled={busy} type="button" onClick={() => void patch({ action: 'set_status', id: selected.id, status: 'archived' })} className="action-secondary"><Archive size={15} />Archive</button></div>
      </div>}
    </section>
    <style jsx>{`.icon-button{display:flex;height:36px;width:36px;align-items:center;justify-content:center;border:1px solid rgba(255,255,255,.1);color:#d4d4d8}.icon-button:hover,.action-secondary:hover{background:rgba(255,255,255,.08)}.action-primary,.action-secondary{display:inline-flex;align-items:center;gap:8px;padding:10px 14px;font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.action-primary{background:#6ee7b7;color:#052e2b}.action-secondary{border:1px solid rgba(255,255,255,.12);color:white}.action-primary:disabled,.action-secondary:disabled{opacity:.4}`}</style>
  </div>;
}

function IdentitySettings({ settings, setSettings, busy, onSave }: { settings: Settings; setSettings: (value: Settings) => void; busy: boolean; onSave: () => void }) {
  const field = (key: keyof Settings, label: string) => <label className="text-xs font-bold text-zinc-300">{label}<input value={settings[key] || ''} onChange={(event) => setSettings({ ...settings, [key]: event.target.value })} className="mt-2 w-full border border-white/10 bg-black/25 px-3 py-2 text-sm text-white" /></label>;
  return <div className="border-b border-white/10 bg-cyan-300/[0.04] p-5"><div className="grid gap-4 sm:grid-cols-2">{field('agent_name', 'Agent name')}{field('brokerage_name', 'Brokerage')}{field('phone', 'Phone')}{field('email', 'Email')}{field('license_number', 'License number')}<label className="text-xs font-bold text-zinc-300">Signature<input value={settings.signature || ''} onChange={(event) => setSettings({ ...settings, signature: event.target.value })} className="mt-2 w-full border border-white/10 bg-black/25 px-3 py-2 text-sm text-white" /></label></div><button disabled={busy || !settings.agent_name?.trim()} type="button" onClick={onSave} className="mt-4 inline-flex items-center gap-2 bg-cyan-300 px-3 py-2 text-xs font-black uppercase text-cyan-950"><Save size={14} />Save identity</button></div>;
}

function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char] || char); }
