BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap;
SELECT plan(22);
SET LOCAL request.jwt.claim.role='service_role';
CREATE TEMP TABLE seller_service_assertions(id BIGINT GENERATED ALWAYS AS IDENTITY,passed BOOLEAN NOT NULL,description TEXT NOT NULL);
CREATE FUNCTION pg_temp.seller_service_assert(p_passed BOOLEAN,p_description TEXT) RETURNS VOID LANGUAGE sql AS $$
  INSERT INTO pg_temp.seller_service_assertions(passed,description) VALUES(COALESCE(p_passed,false),p_description);
$$;
DO $$
DECLARE owner UUID:=gen_random_uuid(); client UUID:=gen_random_uuid(); lead UUID:=gen_random_uuid(); book UUID:=gen_random_uuid();
  key UUID:=gen_random_uuid(); token UUID:=gen_random_uuid(); body JSONB; result JSONB; message_id UUID; job_id UUID; failed BOOLEAN;
  publication JSONB:=jsonb_build_object('summary','Approved update','milestones','[]'::jsonb,'checklist','[]'::jsonb,'documents','[]'::jsonb,'notes','NEVER SHARE');
BEGIN
  INSERT INTO auth.users(id,email,email_confirmed_at) VALUES(owner,'service-owner@example.test',now()),(client,'service-client@example.test',now());
  INSERT INTO public.site_config(id,agent_id,owner_id,status) VALUES(gen_random_uuid(),'seller-service-db',owner,'active');
  INSERT INTO public.agent_site_leads(id,agent_id,site,source,name,email,message,metadata) VALUES(lead,'seller-service-db','seller-service-db','seller_plan','Synthetic Seller','service-client@example.test','Synthetic inquiry',
    jsonb_build_object('sellerPlan',jsonb_build_object('requestedContact',jsonb_build_object('granted',true,'capturedAt',now()))));
  failed:=false; BEGIN PERFORM public.seller_case_read(client,lead); EXCEPTION WHEN SQLSTATE 'P0002' THEN failed:=true; END;
  PERFORM pg_temp.seller_service_assert(failed,'another owner cannot read a seller case');
  PERFORM pg_temp.seller_service_assert(NOT has_table_privilege('authenticated','public.seller_cases','SELECT'),'browser roles cannot read case tables directly');
  PERFORM pg_temp.seller_service_assert(NOT has_function_privilege('anon','public.seller_case_action(uuid,jsonb)','EXECUTE'),'anonymous clients cannot call case mutation RPCs');
  body:=jsonb_build_object('leadId',lead,'expectedRevision',1,'requestKey',key,'action','save_case','propertyId',NULL,'notes','INTERNAL NOTE','documents','[]'::jsonb,'checklist','[]'::jsonb);
  result:=public.seller_case_action(owner,body);
  PERFORM pg_temp.seller_service_assert((result->>'revision')::INTEGER=2,'saving a new case consumes one revision');
  result:=public.seller_case_action(owner,body);
  PERFORM pg_temp.seller_service_assert(result->>'replayed'='true' AND (SELECT revision FROM public.seller_cases WHERE lead_id=lead)=2,'lost-response retry returns its original receipt without another revision');
  failed:=false; BEGIN PERFORM public.seller_case_action(owner,body||jsonb_build_object('notes','Changed')); EXCEPTION WHEN SQLSTATE 'PT409' THEN failed:=true; END;
  PERFORM pg_temp.seller_service_assert(failed,'changed retry payload cannot reuse an operation key');
  failed:=false; BEGIN PERFORM public.seller_case_action(owner,body||jsonb_build_object('requestKey',gen_random_uuid())); EXCEPTION WHEN SQLSTATE 'PT409' THEN failed:=true; END;
  PERFORM pg_temp.seller_service_assert(failed,'a stale case revision is a nonretryable conflict');
  PERFORM public.seller_case_action(owner,jsonb_build_object('leadId',lead,'expectedRevision',2,'requestKey',gen_random_uuid(),'action','milestone','milestone','listing_agreement_verified','occurredOn',(now() AT TIME ZONE 'America/Chicago')::DATE,'evidence','Executed agreement checked'));
  PERFORM public.seller_case_action(owner,jsonb_build_object('leadId',lead,'expectedRevision',3,'requestKey',gen_random_uuid(),'action','publish_progress','reviewed',true,'publication',publication));
  PERFORM public.seller_case_action(owner,jsonb_build_object('leadId',lead,'expectedRevision',4,'requestKey',gen_random_uuid(),'action','share_progress','enabled',true));
  PERFORM pg_temp.seller_service_assert((SELECT count(*) FROM public.seller_client_progress(client))=1,'a matching verified email sees an enabled publication');
  PERFORM pg_temp.seller_service_assert((SELECT count(*) FROM public.seller_client_progress(owner))=0,'a different verified email cannot read the client publication');
  PERFORM pg_temp.seller_service_assert(NOT EXISTS(SELECT 1 FROM public.seller_client_progress(client) p WHERE p::TEXT LIKE '%INTERNAL NOTE%' OR p::TEXT LIKE '%NEVER SHARE%'),'client publication is a database whitelist even for service-supplied extra fields');
  UPDATE public.agent_site_leads SET email='changed@example.test' WHERE id=lead;
  PERFORM pg_temp.seller_service_assert((SELECT count(*) FROM public.seller_client_progress(client))=0,'changing the current seller email removes client access');
  UPDATE public.agent_site_leads SET email='service-client@example.test' WHERE id=lead;
  PERFORM public.seller_case_action(owner,jsonb_build_object('leadId',lead,'expectedRevision',5,'requestKey',gen_random_uuid(),'action','retract_milestone','eventId',(SELECT id FROM public.seller_case_events WHERE lead_id=lead AND kind='milestone'),'reason','Correct incorrect evidence'));
  PERFORM pg_temp.seller_service_assert(NOT public.seller_service_active_milestone(lead,'listing_agreement_verified') AND (SELECT count(*) FROM public.seller_client_progress(client))=0,'milestone correction retains history but withdraws the stage and publication');
  INSERT INTO public.scheduling_bookings(id,uid,title,start_time,end_time,status,funnel_id,lead_id,agent_id,site,appointment_type) VALUES(book,book::TEXT,'Consultation',date_trunc('minute',now())+INTERVAL '1 day',date_trunc('minute',now())+INTERVAL '1 day 1 hour','accepted',gen_random_uuid(),lead,'seller-service-db','seller-service-db','seller_consultation');
  result:=public.seller_case_action(owner,jsonb_build_object('leadId',lead,'expectedRevision',6,'requestKey',gen_random_uuid(),'action','link_booking','bookingId',book));
  PERFORM pg_temp.seller_service_assert(result#>>'{details,consultationEventId}' IS NOT NULL AND (SELECT count(*) FROM public.seller_case_booking_links WHERE lead_id=lead)=1,'accepted authoritative booking produces one consultation link');
  UPDATE public.scheduling_bookings SET status='cancelled' WHERE id=book;
  PERFORM pg_temp.seller_service_assert((SELECT count(*) FROM public.seller_lead_events WHERE lead_id=lead AND event_type='consultation_cancelled')=1,'booking cancellation records a source cancellation');
  body:=jsonb_build_object('leadId',lead,'expectedRevision',(SELECT revision FROM public.seller_cases WHERE lead_id=lead),'requestKey',gen_random_uuid(),'action','send_email','reviewed',true,'fromAddress','Verified <sender@example.test>','expectedLeadRevision',(SELECT revision FROM public.agent_site_leads WHERE id=lead),'subject','Synthetic email','body','Synthetic reviewed body');
  result:=public.seller_case_action(owner,body); message_id:=(result#>>'{details,messageId}')::UUID;
  SELECT m.job_id INTO job_id FROM public.seller_case_messages m WHERE id=message_id;
  PERFORM public.seller_case_action(owner,body);
  PERFORM pg_temp.seller_service_assert((SELECT count(*) FROM public.workflow_jobs j WHERE j.id=job_id)=1 AND (SELECT count(*) FROM public.seller_lead_events WHERE lead_id=lead AND event_type='contact_attempted')=0,'queueing and replay create one durable job without recording contact');
  UPDATE public.workflow_jobs j SET status='running',lease_token=token,lease_until=now()+INTERVAL '5 minutes' WHERE j.id=job_id;
  result:=public.seller_email_prepare(job_id,token,'Changed sender <changed@example.test>');
  PERFORM pg_temp.seller_service_assert(result->>'send'='true' AND result->>'from'='Verified <sender@example.test>','a live worker uses the frozen reviewed sender');
  failed:=false; BEGIN PERFORM public.seller_email_accept(job_id,gen_random_uuid(),'synthetic-receipt'); EXCEPTION WHEN SQLSTATE 'PT409' THEN failed:=true; END;
  PERFORM pg_temp.seller_service_assert(failed,'a stale worker cannot persist an email receipt');
  PERFORM public.seller_email_delivery('synthetic-event','synthetic-provider','delivered',now());
  PERFORM public.seller_email_accept(job_id,token,'synthetic-provider');
  PERFORM pg_temp.seller_service_assert((SELECT status FROM public.seller_case_messages WHERE id=message_id)='delivered' AND (SELECT status FROM public.workflow_jobs j WHERE j.id=job_id)='completed','early verified delivery reconciles atomically with provider acceptance and job completion');
  PERFORM pg_temp.seller_service_assert((SELECT count(*) FROM public.seller_lead_events WHERE lead_id=lead AND event_type='contact_attempted')=1,'provider acceptance records contact exactly once');
  PERFORM public.seller_offer_record('seller-service-db','seller-service-db',key,'visit','synthetic-campaign');
  PERFORM public.seller_offer_record('seller-service-db','seller-service-db',key,'visit','synthetic-campaign');
  PERFORM pg_temp.seller_service_assert((SELECT count(*) FROM public.seller_offer_events WHERE agent_id='seller-service-db')=1,'anonymous offer observations deduplicate by visit and action');
  PERFORM pg_temp.seller_service_assert(NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='seller_offer_events' AND column_name IN ('email','name','ip','referrer','address')),'offer event storage has no personal identity or raw referrer columns');
  UPDATE public.site_config SET owner_id=client WHERE agent_id='seller-service-db';
  failed:=false; BEGIN PERFORM public.seller_case_read(client,lead); EXCEPTION WHEN SQLSTATE 'P0002' THEN failed:=true; END;
  PERFORM pg_temp.seller_service_assert(failed,'site transfer never hands the prior owner private case history to the new owner');
END $$;
SELECT ok(passed,description) FROM seller_service_assertions ORDER BY id;
SELECT * FROM finish();
ROLLBACK;
