'use client';
import React, { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { VibePageHeader } from '../_components/VibePageHeader';
type Theme = { id: string; name: string; version: string; description: string; author: string; templates: Record<string, string>; supportedBlocks: string[] };
export function ThemeDirectory() { const router = useRouter(); const params = useSearchParams(); const siteId = params.get('siteId')?.trim() || ''; const [site, setSite] = useState(siteId); const [themes, setThemes] = useState<Theme[]>([]); const [active, setActive] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState('');
  useEffect(() => { if (!siteId) return; const controller = new AbortController(); fetch(`/api/vibes/themes?siteId=${encodeURIComponent(siteId)}`, { signal: controller.signal }).then(async (response) => { const body = await json(response); if (!response.ok) throw new Error(body?.error || 'Themes could not be loaded.'); setThemes(Array.isArray(body?.themes) ? body.themes : []); setActive(body?.activeThemeId || ''); }).catch((error: Error) => { if (error.name !== 'AbortError') setMessage(error.message); }); return () => controller.abort(); }, [siteId]);
  async function activate(themeId: string) { setBusy(themeId); setMessage(''); try { const response = await fetch(`/api/vibes/themes?siteId=${encodeURIComponent(siteId)}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ themeId }) }); const body = await json(response); if (!response.ok) throw new Error(body?.error || 'Theme could not be activated.'); setActive(themeId); setMessage('Theme activated.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Theme could not be activated.'); } finally { setBusy(''); } }
  return <main className="min-h-screen bg-slate-100 px-4 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-7xl"><VibePageHeader eyebrow="Appearance" title="Themes" description="Choose the presentation package used by this site." /><form className="mb-5 flex gap-2 bg-white p-4" onSubmit={(event) => { event.preventDefault(); router.push(`/vibes/appearance?siteId=${encodeURIComponent(site.trim())}`); }}><label className="flex-1 text-sm font-semibold">Site ID<input required value={site} onChange={(event) => setSite(event.target.value)} className="mt-1 w-full rounded border px-3 py-2 font-normal" /></label><button className="self-end rounded bg-[#2271b1] px-4 py-2 text-sm font-semibold text-white">Open themes</button></form>{message ? <p role="status" className="mb-4 border-l-4 border-[#2271b1] bg-white p-3 text-sm">{message}</p> : null}{siteId ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{themes.map((theme) => <article key={theme.id} className="overflow-hidden border border-slate-300 bg-white"><div className="aspect-[4/3] bg-gradient-to-br from-slate-950 via-amber-950 to-amber-400 p-6 text-white"><div className="border border-white/50 p-5"><p className="text-xs uppercase tracking-widest">{theme.author}</p><p className="mt-8 text-3xl font-serif">{theme.name}</p><p className="mt-2 text-sm">Structured pages and editorial content</p></div></div><div className="p-4"><div className="flex justify-between"><h2 className="font-semibold">{theme.name}</h2>{active === theme.id ? <span className="text-xs font-bold text-emerald-700">Active</span> : null}</div><p className="mt-2 text-sm text-slate-600">{theme.description}</p><p className="mt-2 text-xs text-slate-500">Version {theme.version} · {theme.supportedBlocks.length} blocks</p><button type="button" disabled={active === theme.id || busy !== ''} onClick={() => void activate(theme.id)} className="mt-4 rounded border border-[#2271b1] px-3 py-2 text-sm font-semibold text-[#2271b1] disabled:opacity-40">{busy === theme.id ? 'Activating…' : active === theme.id ? 'Active theme' : 'Activate'}</button></div></article>)}</div> : <p className="border-l-4 border-[#2271b1] bg-white p-4 text-sm">Enter a site ID to manage its theme.</p>}</div></main>; }
async function json(response: Response): Promise<any> { const text = await response.text(); if (!text.trim()) return null; try { return JSON.parse(text); } catch { return null; } }
