'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Revision = { _id: string; revisionNumber: number; createdBy?: string; createdAt?: string; publishedAt?: string; changeSummary?: string; contentHash?: string };
export function RevisionList({ vibeId }: { vibeId: string }) {
  const [revisions, setRevisions] = useState<Revision[] | null>(null);
  const [publishedId, setPublishedId] = useState<string | null>(null);
  useEffect(() => { fetch(`/api/vibes/${encodeURIComponent(vibeId)}/revisions`).then((response) => response.json()).then((payload) => { setRevisions(payload.revisions || []); setPublishedId(payload.publishedRevisionId || null); }).catch(() => setRevisions([])); }, [vibeId]);
  if (!revisions) return <p className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Loading revisions…</p>;
  if (revisions.length === 0) return <p className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">No immutable revisions yet.</p>;
  return <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Revision</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Author</th><th className="px-4 py-3">State</th><th className="px-4 py-3">Summary</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{revisions.map((revision, index) => { const previous = revisions[index + 1]; return <tr key={revision._id}><td className="px-4 py-3 font-bold">r{revision.revisionNumber}</td><td className="px-4 py-3 text-xs text-slate-500">{revision.createdAt ? new Date(revision.createdAt).toLocaleString() : '—'}</td><td className="px-4 py-3 text-xs">{revision.createdBy || '—'}</td><td className="px-4 py-3">{publishedId === revision._id ? <span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-bold text-emerald-800">Published</span> : revision.publishedAt ? <span className="text-xs text-slate-500">Published</span> : <span className="text-xs text-slate-500">Checkpoint</span>}</td><td className="max-w-xs truncate px-4 py-3 text-xs text-slate-600">{revision.changeSummary || '—'}</td><td className="px-4 py-3 text-right">{previous ? <Link href={`/vibes/${encodeURIComponent(vibeId)}/compare?from=${encodeURIComponent(previous._id)}&to=${encodeURIComponent(revision._id)}`} className="text-xs font-bold text-slate-700 hover:underline">Compare</Link> : <span className="text-xs text-slate-400">Baseline</span>}</td></tr>; })}</tbody></table></div>;
}
